name: CD

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Push To GitHub Container Registry
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: tkhshtsh0917/python-sample-prod
          tag_with_ref: true
