name: CI

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image For Development
        run: docker build . --file Dockerfile --target development --tag python-sample-dev-image:latest

      - name: Lint Check & Testing
        run: docker run --rm --name python-sample-dev-container python-sample-dev-image:latest
