name: CI

on: push

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image For Development
        run: docker build . --file Dockerfile --target development --tag python-sample-dev-image:latest

      - name: Lint Check & Testing
        run: docker run -it --rm --name python-sample-dev-container python-sample-dev-image:latest

  build_image:
    name: Build Image
    runs-on: ubuntu-latest
    needs: tests
    if: ${{ success() }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image For Production
        run: docker build . --file Dockerfile --target production --tag python-sample-prod-image:latest

      - name: Production Run
        run: docker run -it --rm --name python-sample-prod-container python-sample-prod-image:latest 1 2
